# docker-compose for development setup
version: '3'

services:
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./api/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 3000
    ports:
      - 3000:3000
      - 5858:5858
    volumes:
      - ./api:/app:delegated
    command: sh -c "npm run start:dev"
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./web/Dockerfile
    environment:
      NODE_ENV: development
      PORT: 8080
    ports:
      - 8080:8080
    volumes:
      - ./web:/app:delegated
    command: sh -c "npm run start:dev"