# .circleci/config.yml
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@8.2.1

workflows:
  main:
    jobs:
      - build-and-push-image:
          context:
            - aws-ecr
          filters:
            branches:
              only: main
jobs:
  build-and-push-image:
    docker:
      - image: cimg/base:2022.12
    resource_class: small
    environment:
      AWS_REGION: us-east-1
      AWS_ECR_REGISTRY_ID: "352871558742"
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
      - aws-ecr/build-and-push-image:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-cli-version: latest
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          path: lambdas/projections
          platform: linux/amd64
          push-image: true
          registry-id: AWS_ECR_REGISTRY_ID
          repo: projections
          tag: "latest"
